server:
  port: 8090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
